Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using VpetsofttNet.Models;

namespace VpetsofttNet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Nosotros()
        {
            return View();
        }

        public IActionResult Modulos()
        {
            return View();
        }

        public IActionResult Error_404()
        {
            return View();
        }

        public IActionResult Contactenos()
        {
            return View();
        }

        public IActionResult InicioSesion()
        {
            return View();
        }
        public IActionResult Registrarse()
        {
            return View();
        }
        public IActionResult Olvcon()
        {
            return View();
        }
        public IActionResult Avg_Tabla_Ingresos()
        {
            return View();
        }
        public IActionResult avg_Formulario_perfil_recep()
        {
            return View();
        }
        public IActionResult avg_tabla_notif_recepcion()
        {
            return View();
        }
        public IActionResult avg_Formulario_mascota()
        {
            return View();
        }
        public IActionResult avg_Formulario_empleados()
        {
            return View();
        }
        public IActionResult avg_Formulario_cliente()
        {
            return View();
        }
        public IActionResult avg_Formulario_citas()
        {
            return View();
        }
        
    }
}

Controllers/IniciarSesionController.cs
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using VpetsofttNet.Datos;
using VpetsofttNet.Models;
using System;

namespace VpetsofttNet.Controllers
{
    public class IniciarSesionController : Controller
    {
        private readonly string _connectionString;

        [HttpGet]
        public IActionResult InicioSesion()
        {
            return View("~/Views/Home/InicioSesion.cshtml");
        }

        [HttpPost] 
        public IActionResult Login(String email, String password)
        {
            bool checkUser = false;
            ConexionBD conexionBD = new ConexionBD();
            String query = "SELECT * FROM empleado WHERE corempleado='"+email+"' AND password='"+password+"' ";

            MySqlCommand cmd = new MySqlCommand(query, conexionBD.AbrirConexion());

            using (MySqlDataReader lector =cmd.ExecuteReader())
            {
                if (lector.HasRows)
                {
                    while (lector.Read())
                    {
                        checkUser = true;
                    }
                }
            }
            if (checkUser == true)
            {
                return RedirectToAction("Avg_Tabla_Ingresos", "Home");
            }else
            {
                // Autenticación fallida
                // Aquí puedes mostrar un mensaje de error al usuario
                ViewBag.ErrorMessage = "Correo electrónico o contraseña incorrectos";
                return View("~/Views/Home/InicioSesion.cshtml");
            }
        }
    }
}

Views/Home/avg_Formulario_citas.cshtml
@model VpetsofttNet.Controllers.AppController

<!DOCTYPE html>
<html>
    <head>
        <title>Formulario_citas</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="shortcut icon" href="/Imegenes/logo1.png">
        <link rel="stylesheet" href="/CSS/avg_encabezado.css">
        <link rel="stylesheet" href="/CSS/avg_Formulario_citas.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    </head>
<body>
    <nav id="nav_formulario_citas">
        <ul>
            <li>
                <a href="#" class="logo">
                    <img src="/Imegenes/logo.png" alt="">
                    <span class="nav-item">Citas e Ingresos</span>
                </a>
            </li>
            <li><a asp-controller="Home" asp-action="Avg_Tabla_Ingresos">
                <i class="fas fa-home"></i>
                <span class="nav-item">Inicio</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_Formulario_cliente">
                <i class="fas fa-wallet"></i>
                <span class="nav-item">Propietario / Mascota</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_Formulario_citas">
                <i class="fas fa-chart-bar"></i>
                <span class="nav-item">Citas</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_Formulario_empleados">
                <i class="fas fa-cog"></i>
                <span class="nav-item">Equipo de trabajo</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_Formulario_perfil_recep">
                <i class="fas fa-user"></i>
                <span class="nav-item">Perfil</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_tabla_notif_recepcion">
                <i class="fas fa-tasks"></i>
                <span class="nav-item">Notificaciones</span>
            </a></li>
           <!-- <li><a href="#">
                <i class="fas fa-question-circle"></i>
                <span class="nav-item">Ayuda</span> 
            </a></li>-->
            <li><a asp-controller="Home" asp-action="Index">
                <i class="fas fa-sign-out-alt"></i>
                <span class="nav-item">Salir</span> 
            </a></li>
        </ul>
    </nav>
    <div class="main-content">
        <header>
            <h2>
                <label>
                    <span class="las la-bars"></span>
                </label>
                Dogsano
            </h2>
            <div class="search-wrapper">
                <span class="las la-search"></span>
                <input type="search" placeholder="Buscar"/>
            </div>

            <div class="user-wrapper">
                <img src="/Imegenes/recepcionista_perfil.jpg" width="40px"height="40px" alt="">
                <div>
                    <h4>CATALINA RUIZ MENDEZ</h4>
                    <small>RECEPCIONISTA</small>
                </div>
            </div>
        </header>
    </div>
    <br><br><br><br>
	<main>
        <h1>AGENDAMIENTO CITAS</h1>
        <br><br>
		<form action="" class="formulario" id="formulario">
			<!-- Grupo: Nombre Usuario -->
            <div class="formulario__grupo" id="Nombre_pro">
				<label for="Nombre_pro" class="formulario__label">Nombre Propietario (Confirmar)</label>
				<div class="formulario__grupo-input">
					<input type="text" class="formulario__input" name="Nombre_pro" id="Nombre_pro" placeholder="David Fernando" readonly  value>
				</div>
			</div>
            <div class="formulario__grupo" id="Apellidos_pro">
				<label for="Apellidos_pro" class="formulario__label">Apellidos Propietario (Confirmar)</label>
				<div class="formulario__grupo-input">
					<input type="text" class="formulario__input" name="Apellidos_pro" id="Apellidos_pro" placeholder="Cifuentes Cardozo" readonly  value>
				</div>
			</div>
            <div class="formulario__grupo">
                <label>Mascota</label>
                <select name="idMascota">
                    <option selected disabled>Seleccione mascota</option>
                    @if (Model != null)
                    {
                        @Html.Raw(Model.ObtenerOpcionesMascotas())
                    }
                    else
                    {
                        <option value="">Error al cargar las mascotas</option>
                    }
                </select>
            </div>
            <div class="formulario__grupo" id="Fecha_cita">
				<label for="Fecha_cita" class="formulario__label">Fecha</label>
				<div class="formulario__grupo-input">
					<input type="date" class="formulario__input" name="Fecha_cita" id="Fecha_cita">
				</div>
			</div>	
            <div class="formulario__grupo">
                <label>Veterinarios</label>
                <select>
                    <option selected disabled>Seleccione un veterinario</option>
                    <option>Samuel Burbano</option>
                    <option>Leonardo Reyes</option>
                    <option>Paola Martelo</option>
                    <option>Adriana Lina</option>
                    <option>Johanna Fuentes</option>
                    <option>Tatiana Moreno</option>
                    <option>Gloria Hernandez</option>
                    <option>Nuria Sotelo</option>
                    <option>Giovanny Gomez</option>
                </select>
            </div>	
            <div class="formulario__grupo">
                <label>Especialidad</label>
                <select>
                    <option selected disabled>Seleccione una especialidad</option>
                    <option>Medicina general</option>
                    <option>Cirugia</option>
                    <option>Terapias</option>
                    <option>Toma de muestras</option>
                    <option>Imagenes Diagnosticas</option>
                    <option>Odontologia</option>
                    <option>Vacunacion</option>
                </select>
                <br><br><br>
            </div>		
		
			<div class="formulario__grupo formulario__grupo-btn-enviar">
				<button type="submit" class="formulario__btn" onclick="location.href='tabla_citas.html'">Buscar</button>
			</div>
		</form>
	</main>
</body>
</html>

Views/Home/avg_Formulario_cliente.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>Formulario_cliente</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="shortcut icon" href="/Imegenes/logo1.png">
        <link rel="stylesheet" href="/CSS/avg_encabezado.css">
        <link rel="stylesheet" href="/CSS/agv_Formulario_cliente.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    </head>
<body>
    <nav id="nav_formulario_cliente">
        <ul>
            <li>
                            <a href="#" class="logo">
                                <img src="/Imegenes/logo.png" alt="">
                                <span class="nav-item">Citas e Ingresos</span>
                            </a>
                        </li>
                        <li><a asp-controller="Home" asp-action="Avg_Tabla_Ingresos">
                            <i class="fas fa-home"></i>
                            <span class="nav-item">Inicio</span>
                        </a></li>
                        <li><a asp-controller="Home" asp-action="avg_Formulario_cliente">
                            <i class="fas fa-wallet"></i>
                            <span class="nav-item">Propietario / Mascota</span>
                        </a></li>
                        <li><a asp-controller="Home" asp-action="avg_Formulario_citas">
                            <i class="fas fa-chart-bar"></i>
                            <span class="nav-item">Citas</span>
                        </a></li>
                        <li><a asp-controller="Home" asp-action="avg_Formulario_empleados">
                            <i class="fas fa-cog"></i>
                            <span class="nav-item">Equipo de trabajo</span>
                        </a></li>
                        <li><a asp-controller="Home" asp-action="avg_Formulario_perfil_recep">
                            <i class="fas fa-user"></i>
                            <span class="nav-item">Perfil</span>
                        </a></li>
                        <li><a asp-controller="Home" asp-action="avg_tabla_notif_recepcion">
                            <i class="fas fa-tasks"></i>
                            <span class="nav-item">Notificaciones</span>
                        </a></li>
                       <!-- <li><a href="#">
                            <i class="fas fa-question-circle"></i>
                            <span class="nav-item">Ayuda</span> 
                        </a></li>-->
                        <li><a asp-controller="Home" asp-action="Index">
                            <i class="fas fa-sign-out-alt"></i>
                            <span class="nav-item">Salir</span> 
                        </a></li>
                    </ul>
                </nav>
    <div class="main-content">
        <header>
            <h2>
                <label>
                    <span class="las la-bars"></span>
                </label>
                Dogsano
            </h2>
            <div class="search-wrapper">
                <span class="las la-search"></span>
                <input type="search" placeholder="Buscar"/>
            </div>

            <div class="user-wrapper">
                <img src="/Imegenes/recepcionista_perfil.jpg" width="40px"height="40px" alt="">
                <div>
                    <h4>CATALINA RUIZ MENDEZ</h4>
                    <small>RECEPCIONISTA</small>
                </div>
            </div>
        </header>
    </div>
    <br><br>
	<main>
        <h1>REGISTRO PROPIETARIO</h1>
        <br><br>
		<form action="" class="formulario" id="formulario">
			<!-- Grupo: Nombre Usuario -->
            <div class="formulario__grupo" id="Nombre">
				<label for="Nombre" class="formulario__label">Nombres</label>
				<div class="formulario__grupo-input">
					<input type="text" class="formulario__input" name="Nombre" id="Nombre"  value required>
				</div>
			</div>
            <div class="formulario__grupo" id="Apellidos">
				<label for="Apellidos" class="formulario__label">Apellidos</label>
				<div class="formulario__grupo-input">
					<input type="text" class="formulario__input" name="Apellidos" id="Apellidos"  value required>
				</div>
			</div>
            <!-- Grupo: Cedula -->
			<div class="formulario__grupo" id="Cedula">
				<label for="Cedula" class="formulario__label">Numero de Cedula</label>
				<div class="formulario__grupo-input">
					<input type="number" class="formulario__input" name="Cedula" id="Cedula" step="1" min="10000000" max="1999999999"placeholder="Ingresar numero sin puntos ni comas" required>
				</div>
			</div>
			<div class="formulario__grupo" id="Celular">
				<label for="Celular" class="formulario__label">Numero Celular</label>
				<div class="formulario__grupo-input">
					<input type="number" class="formulario__input" name="Celular" id="Celular"min="3002000000" max="3509999999" value required>
				</div>
			</div>
            <div class="formulario__grupo" id="Email">
				<label for="Email" class="formulario__label">Email</label>
				<div class="formulario__grupo-input">
					<input type="email" class="formulario__input" name="Email" id="Email" required >
				</div>
			</div>
            <div class="formulario__grupo" id="Direccion">
				<label for="Direccion" class="formulario__label">Direccion</label>
				<div class="formulario__grupo-input">
					<input type="text" class="formulario__input" name="Direccion" id="Direccion"  value required>
				</div>
			</div>
            <div class="formulario__grupo">
                <label>Ciudad</label>
                <select>
                    <option selected disabled>Seleccione un valor</option>
                    <option>Bogota</option>
                    <option>Cajica</option>
                    <option>Chia</option>
                    <option>Cota</option>
                    <option>Soacha</option>
                    <option>Facatativa</option>
                </select>
                <br><br><br>
            </div>	
			<div class="formulario__grupo formulario__grupo-btn-enviar">
				<button type="submit" class="formulario__btn">Editar</button>
                
			</div>
            <div>
            <a href="/HTML/avg_Formulario_mascota.html">Crear Mascota</a>
            </div>
		</form>
	</main>
</body>
</html>

Views/Home/avg_Formulario_empleados.cshtml
<!DOCTYPE html>
<html>
    <head>
        <title>Formulario_empleados</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="shortcut icon" href="/Imegenes/logo1.png">
        <link rel="stylesheet" href="/CSS/avg_encabezado.css">
        <link rel="stylesheet" href="/CSS/avg_Formulario_empleados.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    </head>
<body>
    <nav id="nav_formulario_empleados">
        <ul>
<li>
                <a href="#" class="logo">
                    <img src="/Imegenes/logo.png" alt="">
                    <span class="nav-item">Citas e Ingresos</span>
                </a>
            </li>
            <li><a asp-controller="Home" asp-action="Avg_Tabla_Ingresos">
                <i class="fas fa-home"></i>
                <span class="nav-item">Inicio</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_Formulario_cliente">
                <i class="fas fa-wallet"></i>
                <span class="nav-item">Propietario / Mascota</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_Formulario_citas">
                <i class="fas fa-chart-bar"></i>
                <span class="nav-item">Citas</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_Formulario_empleados">
                <i class="fas fa-cog"></i>
                <span class="nav-item">Equipo de trabajo</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_Formulario_perfil_recep">
                <i class="fas fa-user"></i>
                <span class="nav-item">Perfil</span>
            </a></li>
            <li><a asp-controller="Home" asp-action="avg_tabla_notif_recepcion">
                <i class="fas fa-tasks"></i>
                <span class="nav-item">Notificaciones</span>
            </a></li>
           <!-- <li><a href="#">
                <i class="fas fa-question-circle"></i>
                <span class="nav-item">Ayuda</span> 
            </a></li>-->
            <li><a asp-controller="Home" asp-action="Index">
                <i class="fas fa-sign-out-alt"></i>
                <span class="nav-item">Salir</span> 
            </a></li>
        </ul>
    </nav>
<div class="main-content">
    <header>
        <h2>
            <label>
                <span class="las la-bars"></span>
            </label>
            Dogsano
        </h2>
        <div class="search-wrapper">
            <span class="las la-search"></span>
            <input type="search" placeholder="Buscar"/>
        </div>

        <div class="user-wrapper">
            <img src="/Imegenes/recepcionista_perfil.jpg" width="40px"height="40px" alt="">
                <div>
                    <h4>CATALINA RUIZ MENDEZ</h4>
                    <small>RECEPCIONISTA</small>
                </div>
            </div>
        </header>
    </div>
    <br><br><br><br>
	<main>
        <h1>REGISTRO EMPLEADOS</h1>
        <br><br>
		<form action="" class="formulario" id="formulario">
			<!-- Grupo: Nombre Usuario -->
            <div class="formulario__grupo" id="Nombre">
				<label for="Nombre" class="formulario__label">Nombres</label>
				<div class="formulario__grupo-input">
					<input type="text" class="formulario__input" name="Nombre" id="Nombre"  value required>
				</div>
			</div>
            <div class="formulario__grupo" id="Apellidos">
				<label for="Apellidos" class="formulario__label">Apellidos</label>
				<div class="formulario__grupo-input">
					<input type="text" class="formulario__input" name="Apellidos" id="Apellidos"  value required>
				</div>
			</div>
            <!-- Grupo: Cedula -->
			<div class="formulario__grupo" id="Cedula">
				<label for="Cedula" class="formulario__label">Numero de Cedula</label>
				<div class="formulario__grupo-input">
					<input type="number" class="formulario__input" name="Cedula" id="Cedula" step="1" min="10000000" max="1999999999"placeholder="Ingresar numero sin puntos ni comas" required>
				</div>
			</div>
            <div class="formulario__grupo" id="Fecha Nacimiento">
				<label for="Fecha Nacimiento" class="formulario__label">Fecha Nacimiento</label>
				<div class="formulario__grupo-input">
					<input type="date" class="formulario__input" name="Fecha Nacimiento" id="Fecha Nacimiento" step="1" min="1" max="3" required>
				</div>
			</div>
			<div class="formulario__grupo" id="Celular">
				<label for="Celular" class="formulario__label">Numero Celular</label>
				<div class="formulario__grupo-input">
					<input type="number" class="formulario__input" name="Celular" id="Celular"min="3002000000" max="3509999999" value required>
				</div>
			</div>
            <div class="formulario__grupo" id="Email">
				<label for="Email" class="formulario__label">Email</label>
				<div class="formulario__grupo-input">
					<input type="email" class="formulario__input" name="Email" id="Email" required >
				</div>
			</div>
            <div class="formulario__grupo" id="Direccion">
				<label for="Direccion" class="formulario__label">Direccion</label>
				<div class="formulario__grupo-input">
					<input type="text" class="formulario__input" name="Direccion" id="Direccion"  value required>
				</div>
			</div>
            <div class="formulario__grupo">
                <label>Especialidad</label>
                <select>
                    <option selected disabled>Seleccione una especialidad</option>
                    <option>Medicina General</option>
                    <option>Cirugia</option>
                    <option>Terapias</option>
                    <option>Toma de muestras</option>
                    <option>Imagenes diagnosticas</option>
                    <option>Odontologia</option>
                    <option>Vacunacion</option>
                    <option>Auxiliar</option>
                </select>
            </div>		
            <div class="formulario__grupo">
                <label>Cargo</label>
                <select>
                    <option selected disabled>Seleccione el cargo</option>
                    <option>Veterinario</option>
                    <option>Recepcionista</option>
                    <option>Almacenista</option>
                </select>
            </div>	
            <div class="formulario__grupo">
                <label>EPS</label>
                <select>
                    <option selected disabled>Seleccione una especialidad</option>
                    <option>Salud Total</option>
                    <option>E.P.S. SANITAS S.A.</option>
                    <option>SOLSALUD E.P.S. S.A.</option>
                    <option>COOMEVA E.P.S. S.A.</option>
                    <option>EMDISALUD</option>
                    <option>ASMET SALUD</option>
                    <option>CRUZ BLANCA E.P.S. S.A.</option>
                    <option>E.P.S. FAMISANAR LIMITADA CAFAM-COLSUBSIDIO</option>
                    <option>CCF COLSUBSIDIO</option>
                    <option>COLMEDICA E.P.S. - ALIANSALUD  </option>
                    <option>COMFACUNDI</option>
                    <option>COMPENSAR E.P.S.</option>
                    <option>SALUD COLPATRIA E.P.S.</option>
                </select>
                <br><br><br>
            </div>	
			<div class="formulario__grupo formulario__grupo-btn-enviar">
				<button type="submit" class="formulario__btn">Guardar</button>
			</div>
		</form>
	</main>
</body>
</html>

Views/Home/contactenos.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contactenos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/CSS/contactenos.css">
    <link rel="stylesheet" href="/CSS/menu.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="/Imegenes/logo1.png">
</head>
<body>
    <!--Etiqueta nav proporciona enlaces de navegación,-->
    <nav>
        <!--se agrega un icono de font awesome para la casilla de verificacion con la clase checkbtn-->
        <input type="checkbox" id="check">
        <label for="check" class="checkbtn">
            <i class="fas fa-bars"></i>
        </label>
        <!--se agrega una clase enlace-->
        <a href="#" class="enlace">
            <!--se agrega el logo para el menu mediante la clase logo-->
            <img src="/Imegenes/logo.png" alt="" class="logo">
            <p class="nombre"><b> VPETSOFT </b></p>
        </a>
        <!--lista de menu-->
        <ul>
            <li><a asp-controller="Home" asp-action="Index" class="active">Inicio</a></li>
            <li><a asp-controller="Home" asp-action="Nosotros">¿Quienes somos?</a></li>
            <li><a asp-controller="Home" asp-action="Modulos">Servicios</a></li>
            <li><a asp-controller="Home" asp-action="Error_404">Red de atencion</a></li>
            <li><a asp-controller="Home" asp-action="Contactenos">Contactenos</a></li>
        </ul>
    </nav>
    <br><br>
    <div class="contenedor">
        <form action="" class="form">
            <div class="form-header">
                <h1 class="form-title">PQR VPETSOFT</h1>
            </div>
            <label for="nombre" class="form-label">Nombres</label>
            <input type="text" id="nombre" class="form-input" placeholder="Escriba sus nombres" required title="No usar numeros para el nombre" pattern="[a-zA-Z]{2,}">
            <label for="apellido" class="form-label">Apellidos</label>
            <input type="text" id="apellido" class="form-input" placeholder="Escriba sus apellidos" required title="No usar numeros para el apellido" pattern="[a-zA-Z]{2,}">
            <label for="correo" class="form-label">Correo</label>
            <input type="email" id="correo" class="form-input" placeholder="Escriba su correo electronico" required> 
            <label for="telefono" class="form-label">Telefono</label>
            <input type="number" minlength="10" maxlength="10" id="telefono" class="form-input" placeholder="Escriba su numero telefonico" required>
            <label for="tipo" class="form-label"> Tipo Solicitud </label>
            <select class="lista" name="pqr">
                <option value="Queja">Queja</option>
                <option value="Solicitud">Solicitud</option>
                <option value="Reclamo">Reclamo</option>
                <option value="Sugerencia">Sugerencia</option>
            </select>
            <label for="descripcion" class="form-label"> Descripcion </label>
            <textarea id="descripcion" class="form-textarea" placeholder="Escriba la descipcion del PQR" required></textarea>
            <input class="btn-submit" type="submit" value="Enviar">
        </form>
    </div>
</body>
</html>

Views/Home/iniciosesion.cshtml
@model empleado
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>INICIO SESION</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../CSS/contactenos.css">
    <link rel="stylesheet" href="../CSS/menu.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="../Imegenes/logo1.png">
</head>
<body>
        <!--Etiqueta nav proporciona enlaces de navegación,-->
        <nav>
            <!--se agrega un icono de font awesome para la casilla de verificacion con la clase checkbtn-->
            <input type="checkbox" id="check">
            <label for="check" class="checkbtn">
                <i class="fas fa-bars"></i>
            </label>
            <!--se agrega una clase enlace-->
            <a href="#" class="enlace">
                <!--se agrega el logo para el menu mediante la clase logo-->
                <img src="/Imegenes/logo.png" alt="" class="logo">
                <p class="nombre"><b> VPETSOFT </b></p>
            </a>
            <!--lista de menu-->
            <ul>
                <!--se agrega los valores para la lista del menu y al valor del inicio se le agrega la clase active-->
                <li><a asp-controller="Home" asp-action="Index" class="active">Inicio</a></li>
                <li><a asp-controller="Home" asp-action="Nosotros">¿Quienes somos?</a></li>
                <li><a asp-controller="Home" asp-action="Modulos">Servicios</a></li>
                <li><a asp-controller="Home" asp-action="Error_404">Red de atencion</a></li>
                <li><a asp-controller="Home" asp-action="Contactenos">Contactenos</a></li>
            </ul>
        </nav>
        <br><br><br>
    <div class="contenedor">
        <form asp-controller="IniciarSesion" asp-action="Login" class="form" method="post">
            <div class="form-header">
                <h1 class="form-title">INICIO SESION</h1>
            </div>
            <label for="nombre" class="form-label">Correo electronico</label>
            <input type="email" id="nombre" name="email" class="form-input" placeholder="Escriba su correo electronico" required>
            <label for="contraseña" class="form-label">Contraseña</label>
            <input type="password" id="contraseña" name="password" class="form-input" placeholder="Escriba su contraseña" required>
            <br>
            <div style="color: red">@ViewBag.ErrorMessage</div>
            <br>
            <input class="btn-submit" type="submit" value="Iniciar sesion">
            <p><a asp-action="Registrarse" class="form-label">¿No tiene cuenta? Registrese acá</a></p>
            <p><a asp-action="Olvcon" class="form-label">¿Olvido su contraseña?</a></p>
        </form>
    </div> 
</body>
</html>